### PR TITLE
update bootstrap theme

### PR DESCRIPTION
**Pull request by FanchTheSystem**
Update bootstrap theme

Allow easy customisation before angular build:
```
cp materia.min.css theme.css
```

From https://bootswatch.com/

### CODE REVIEW

**Comment by osallou** [comment]
Idea is to get custom bootstrap themes?

**Comment by osallou** [comment]
With dark mode? It is hype ;-)

**Comment by osallou** [comment]
In github  diff i do not see a default link to basic bootstrap theme, missing or i missed something?

**Comment by osallou** [comment]
Ok i see a default theme.css... this is the basic bootstrap theme?

**Comment by FanchTheSystem** [comment]
I don't like dark mode, but I can add one if you want ;)

**Comment by FanchTheSystem** [comment]
cerulean

image

image

**Comment by FanchTheSystem** [comment]
materia

image
image

**Comment by FanchTheSystem** [comment]
> In github diff i do not see a default link to basic bootstrap theme, missing or i missed something?

I think it does not work with link so I replace I think cp is better

**Comment by FanchTheSystem** [comment]
spacelab
image
image

**Comment by FanchTheSystem** [comment]
darkly
image
image

**Comment by FanchTheSystem** [comment]
slate
image
image

**Comment by FanchTheSystem** [comment]
superhero
image
image

**Comment by FanchTheSystem** [comment]
@osallou which one you would like as default ?

Please note you have to rebuild angular to change it

**Comment by osallou** [comment]
Cereluan could be default, but can t we specify it as a build arg for docker, with a default

**Comment by FanchTheSystem** [comment]
> Cereluan could be default, but can t we specify it as a build arg for docker, with a default

I added an arg to the docker file https://github.com/genouest/genouestaccountmanager/pull/270/commits/f8c62f7ea14c4f19a6291021d05578e942c7d92b

**Pull request merged**
