### PR TITLE
update package lock, to use lockfileversion 1

### PR DESCRIPTION
**Pull request by FanchTheSystem**
To avoid error like:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

and run npm audit fix

### CODE REVIEW

**Comment by osallou** [comment]
I do not see in package lock (at least) the otplib dep present in package.json

**Comment by FanchTheSystem** [comment]
> I do not see in package lock (at least) the otplib dep present in package.json

line 111:
image

**Comment by osallou** [comment]
Yes , removed....
But it should be present

**Comment by FanchTheSystem** [comment]
yes you are right, maybe it is the diff which is not ok

because the line are present in the file submitted:
https://github.com/FanchTheSystem/genouestaccountmanager/blob/update_lockfile/package-lock.json#L2541-L2549

**Pull request merged**
