### PR TITLE
protect ldap password with quote as it may contain some shell intepreted char

### PR DESCRIPTION
**Pull request by FanchTheSystem**

### CODE REVIEW

**Comment by osallou** [comment]
why not but this is the ldap admin password, so managed by administrator themselves....

**Comment by FanchTheSystem** [comment]
Yes of course, I have generate a strong password for the ldap admin on the ifb core installation (not the cluster one) 

and account creation failed because the ldap password contain shell special char

so the quote solve the issue

maybe one day you will change your ldap password to have a more secure one and will be happy to be able to have $ or @ inside

**Comment by osallou** [comment]
but if you have multiple quote password ?  admin''stuff''' etc... ?

**Comment by FanchTheSystem** [comment]
if you have one or more simple quote in your password it will not work as it is today as they will be interpreted by the shell 

maybe we should add a mention in the doc that ldap password with simple are not supported

**Comment by osallou** [comment]
As better solution, password should be escaped

**Pull request merged**
