### PR TITLE
change projects page order

### PR DESCRIPTION
**Pull request by FanchTheSystem**
to have the same "box" order as in groups or users pages
creation on top, and list at the end

### CODE REVIEW

**Comment by FanchTheSystem** [comment]
Also I think the accept button should be removed. 
As it is useless, it do the same as create, and it may confuse people.

**Comment by osallou** [comment]
Need to check, but with konogan updates i think the accept button prefills the new project fields. @KonoganB ?

**Comment by FanchTheSystem** [comment]
Yes there are 2 button, both pre-fills the fields and the "create" one do also one more task, it call add_project

here is the code:
https://github.com/genouest/genouestaccountmanager/blob/master/manager2/src/app/admin/projects/projects.component.ts#L301-L309

**Comment by osallou** [comment]
ok so you mean to remove accept for automatic accept, and keep only modify to prefill new project, then admin creates it, or not, right?

**Comment by FanchTheSystem** [comment]
> ok so you mean to remove accept for automatic accept, and keep only modify to prefill new project, then admin creates it, or not, right?

Yes it is, and it can be done in another PR (as this one is only for box order)

**Pull request merged**
