### PR TITLE
Add team field + Allow to set Default user Group

### PR DESCRIPTION
**Pull request by FanchTheSystem**

### CODE REVIEW

**Comment by FanchTheSystem** [comment]
@osallou : please could you review this PR ?

Tested on my dev and preprod env, it work, as it add a new field, you may want to run updated mongo_rename_field.sh

**Comment by osallou** [comment]
looks ok, ready for merge?

**Comment by FanchTheSystem** [comment]
yes !

**Comment by FanchTheSystem** [comment]
Please if you can add a tag after merge ;)

**Pull request merged**
