### PR TITLE
use toLocaleString and toLocaleDateString

### PR DESCRIPTION
**Pull request by FanchTheSystem**

### CODE REVIEW

**Comment by FanchTheSystem** [comment]
Maybe with should use toLocaleDateString everywhere as we don't care about minute in My date

**Comment by osallou** [comment]
What is output format?
I think i used specific function to format date because default was display full day instead of numbers, and longer strings rather than 'easy' date format like yy/mm/dd

**Comment by FanchTheSystem** [comment]
> What is output format?
> I think i used specific function to format date because default was display full day instead of numbers, and longer strings rather than 'easy' date format like yy/mm/dd

As it use local, it will depend on user locale config (in browser)
In my config it show: 03/12/2020 with the time or not (depending if we use toLocaleDateString or to LocaleString)

**Comment by FanchTheSystem** [comment]
```
const event = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
console.log(event.toLocaleDateString());
const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
console.log(event.toLocaleDateString('fr-FR', options));
```

Give me

> "20/12/2012"
> "jeudi 20 décembre 2012"

**Pull request merged**
