### PR TITLE
Update package

### PR DESCRIPTION
**Pull request by FanchTheSystem**
This PR is the result of "npm audit fix"

Should not breaking changes as I don't use the force option.

Should solve all the PR from dependabot.

I test it on my dev and preprod environment and remove the WIP in the title when every thing look good

### CODE REVIEW

**Comment by osallou** [comment]
good idea  ;-)
but need tests on UI
On backend should not be too much an issue
Pb is some updates with fixes sometimes break their api.

**Comment by FanchTheSystem** [comment]
Yes I will run my selenium test on UI

**Comment by FanchTheSystem** [comment]
I fix angular build version according to : 
https://github.com/angular/angular-cli/releases/tag/v7.3.10

**Comment by FanchTheSystem** [comment]
I fix typescript version to be compatible with angular compiler version

**Comment by osallou** [comment]
Petit joueur... ;-)

**Comment by FanchTheSystem** [comment]
Test done, it look ok for me

**Comment by osallou** [comment]
thanks. My planning is really "full" this week, will try to check this PR as soon as possible.

**Pull request merged**
