### PR TITLE
Remove accent (and other non alphanum char) from userid

### PR DESCRIPTION
**Pull request by FanchTheSystem**
https://gitlab.com/ifb-elixirfr/ansible-roles/ansible-my/issues/10

### CODE REVIEW

**Comment by lecorguille** [comment]
It's remove or replace?
é -> e
ö -> o

**Comment by osallou** [comment]
remove...

**Comment by lecorguille** [comment]
Hum, I will be sad if I lost my terminal e
Le Corguillé -> lecorguill

And I guess that it's worse but the accent is in the middle of the name :/

Gèrbe -> grbe

:P

**Comment by FanchTheSystem** [comment]
@lecorguille : you can still add it by hand, if you insist I will propose another fix after my vacation ;)

**Pull request merged**
