### PR TITLE
Remove pending user in project (auto add if owner)

### PR DESCRIPTION
**Pull request by FanchTheSystem**

### CODE REVIEW

**Comment by FanchTheSystem** [comment]
I will rebase when #254  will be merged

**Comment by FanchTheSystem** [comment]
Related: https://github.com/genouest/genouestaccountmanager/issues/252

**Comment by osallou** [comment]
in web ui, project owner have access to add/remove users?

**Comment by FanchTheSystem** [comment]
> in web ui, project owner have access to add/remove users?

yes on the project page (you have to test with a not admin account to see it)

**Pull request merged**
