### PR TITLE
Feature multiexpirenotif

### PR DESCRIPTION
**Pull request by osallou**
on user expiration, send multiple notification emails

### CODE REVIEW

**Comment by FanchTheSystem** [comment]
@osallou : maybe we should merge this will conflict are minor

**Comment by osallou** [comment]
need to fix conflict

you really want to check all users expiration every day?

**Comment by FanchTheSystem** [comment]
at ifb and abims we use  systemd timer to launch script, so modification on gomngr.sh will not have impact on our side

**Comment by FanchTheSystem** [comment]
We plan to enable user and project expiration in few day/week.

So I think we will need an option to send mail to admin too.

And maybe a way to disable expiration the first month (only send mail, and don't change user password)

**Comment by osallou** [comment]
if you want

**Comment by FanchTheSystem** [comment]
conflict solved ;)

**Comment by FanchTheSystem** [comment]
About config option, After reading the code. 

I think the second one is useless, the simplest way to do it is to disable the expiration is to disable the launch the expire.js script, (and it is easy to do it for ifb and abims as we use systemd timer)

**Comment by FanchTheSystem** [comment]
https://github.com/genouest/genouestaccountmanager/pull/306

**Pull request merged**
